"""Portable reproduction of the same figure from the adjacent CSV only.

python plot.py --output /output/coupled_member_grading_mass.png
The thesis handoff PNG is generated by plot_material_distribution.m.
"""
from pathlib import Path
import argparse
import csv
import math

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

FOLDER = Path(__file__).resolve().parent
parser = argparse.ArgumentParser()
parser.add_argument("--output", default="coupled_member_grading_mass_python.png")
args = parser.parse_args()
destination = Path(args.output).resolve()
if destination.suffix.lower() not in {".png", ".pdf", ".svg"}:
    raise ValueError("Output extension must be PNG, PDF or SVG")
if not destination.parent.is_dir():
    raise FileNotFoundError(destination.parent)
with (FOLDER / "selected_material_distribution.csv").open(newline="", encoding="utf-8") as stream:
    data = list(csv.DictReader(stream))
assert [int(r["Case"]) for r in data] == [4, 37, 64, 99]
for row in data:
    assert math.isclose(float(row["SkinMassTwoWing_kg"]) + float(row["LatticeMassTwoWing_kg"]),
                        float(row["TotalMassTwoWing_kg"]), abs_tol=1e-9)
colors = [(0.16,0.16,0.16),(0.086,0.486,0.714),(0.396,0.486,0.153),(0.863,0.478,0.094)]
styles = ["-", "--", "-.", ":"]
markers = ["o", "s", "^", "D"]
labels = ["4 (initial)", "37 (adaptive)", "64 (adaptive)", "99 (adaptive)"]
plt.rcParams.update({"font.family":"serif", "font.serif":["Times New Roman","DejaVu Serif"],
                     "font.size":10,"axes.linewidth":0.65,"mathtext.fontset":"stix"})
fig = plt.figure(figsize=(19/2.54,10.6/2.54),facecolor="white")
diameter = fig.add_axes([0.086,0.23,0.390,0.59])
mass = fig.add_axes([0.568,0.23,0.380,0.59])
for ax in [diameter,mass]:
    ax.spines[["top","right"]].set_visible(False)
    ax.tick_params(direction="out")
    ax.grid(axis="y",color="0.90",linewidth=0.6)
    ax.set_axisbelow(True)
lines=[]
eta=[i/100 for i in range(101)]
for row,color,style,marker,label in zip(data,colors,styles,markers,labels):
    root,tip=float(row["RootDiameter_mm"]),float(row["TipDiameter_mm"])
    line,=diameter.plot(eta,[root+(tip-root)*x for x in eta],color=color,linestyle=style,linewidth=1.65,label=label)
    diameter.plot([0,1],[root,tip],linestyle="none",marker=marker,markersize=4.3,
                  markerfacecolor="white",color=color,clip_on=False)
    lines.append(line)
diameter.set(xlim=(0,1),ylim=(0,10),xticks=[0,.25,.5,.75,1],yticks=range(0,11,2),
             xlabel=r"Normalized semispan, $\eta=y/s$",ylabel="Nominal diameter [mm]")
diameter.set_title("(a) Prescribed member grading",fontsize=11,pad=14)
for index,(row,color) in enumerate(zip(data,colors),start=1):
    skin,lattice,total=[float(row[k]) for k in ["SkinMassTwoWing_kg","LatticeMassTwoWing_kg","TotalMassTwoWing_kg"]]
    mass.bar(index,skin,width=.62,color="white",edgecolor=color,linewidth=1.2)
    mass.bar(index,lattice,bottom=skin,width=.62,color=color,edgecolor=color,linewidth=1.2)
    mass.text(index,skin/2,f"{skin:.2f}",ha="center",va="center",fontsize=9,color="0.2")
    mass.text(index,total+2.6,f"{total:.2f}",ha="center",va="bottom",fontsize=9.3)
mass.set(xlim=(.4,4.6),ylim=(0,115),xticks=range(1,5),xticklabels=[r["Case"] for r in data],
         yticks=range(0,101,20),xlabel="Case",ylabel="Two-wing optimization mass [kg]")
mass.set_title("(b) Skin and lattice mass",fontsize=11,pad=14)
mass.legend(handles=[Patch(facecolor="white",edgecolor=".25",label="Skin"),
                     Patch(facecolor=".3",edgecolor=".25",label="Implicit lattice")],
            loc="upper right",frameon=False,fontsize=9.3,handlelength=1.3)
fig.legend(lines,labels,ncol=4,loc="upper center",bbox_to_anchor=(.515,.97),
           frameon=False,fontsize=9.3,handlelength=2.2,columnspacing=1.5)
fig.text(.515,.085,r"Prescribed linear law: $t(\eta)=t_1+(t_2-t_1)\eta$; evaluated endpoint parameters.",
         ha="center",va="center",fontsize=9)
fig.text(.515,.044,"Mass labels show skin contributions and totals; lattice mass uses the implicit geometry.",
         ha="center",va="center",fontsize=9)
fig.savefig(destination,dpi=600,facecolor="white")
plt.close(fig)
print(destination)
