function [evaluations, continuation, config, expected] = ...
        load_topology_data(topology)
%LOAD_TOPOLOGY_DATA Load and validate one packaged topology dataset.

topology = lower(string(topology));
if ~ismember(topology, ["fcc", "bcc"])
    error("artifacts:UnknownTopology", ...
        "Topology must be either 'fcc' or 'bcc'.");
end

root = artifact_repository_root();
config = jsondecode(fileread(fullfile( ...
    root, "config", "reproduction_config.json")));
expected = config.(char(topology));
dataDirectory = fullfile(root, "data", topology);

evaluations = readtable(fullfile(dataDirectory, ...
    "evaluations_cases001_071.csv"), ...
    TextType="string", VariableNamingRule="preserve");
continuation = readtable(fullfile(dataDirectory, ...
    "continuation_cases052_071.csv"), ...
    TextType="string", VariableNamingRule="preserve");

logicalEvaluationColumns = ["feasible", "pareto_case071"];
for column = logicalEvaluationColumns
    evaluations.(column) = logical(evaluations.(column));
end
logicalContinuationColumns = [ ...
    "stress_ok", "flutter_ok", "trim_ok", "simulation_ok", ...
    "feasible", "pareto_case071", "fallback_used"];
for column = logicalContinuationColumns
    continuation.(column) = logical(continuation.(column));
end

assert(height(evaluations) == expected.expected_total_evaluations, ...
    "Unexpected number of %s evaluation rows.", topology);
assert(height(continuation) == ...
    expected.expected_continuation_evaluations, ...
    "Unexpected number of %s continuation rows.", topology);
assert(isequal(evaluations.case_id, ...
    (1:expected.expected_total_evaluations)'), ...
    "%s evaluation case indices are not contiguous.", topology);
assert(isequal(continuation.case_id, ...
    (config.continuation_first_case:config.final_case)'), ...
    "%s continuation case indices are not contiguous.", topology);
end

