function [evaluations, continuation, config, expected] = ...
        load_topology_data(topology)
%LOAD_TOPOLOGY_DATA Load and validate one packaged topology dataset.

topology = lower(string(topology));
if ~ismember(topology, ["fcc", "bcc", "sc"])
    error("artifacts:UnknownTopology", ...
        "Topology must be 'fcc', 'bcc', or 'sc'.");
end

root = artifact_repository_root();
config = jsondecode(fileread(fullfile( ...
    root, "config", "reproduction_config.json")));
expected = config.(char(topology));
dataDirectory = fullfile(root, "data", topology);

evaluations = readtable(fullfile(dataDirectory, ...
    "evaluations_cases001_071.csv"), ...
    TextType="string", VariableNamingRule="preserve");
continuation = readtable(fullfile(dataDirectory, ...
    "continuation_cases052_071.csv"), ...
    TextType="string", VariableNamingRule="preserve");

evaluationLogical = intersect( ...
    ["feasible", "pareto_case071"], ...
    string(evaluations.Properties.VariableNames), "stable");
for column = evaluationLogical
    evaluations.(column) = to_logical_column(evaluations.(column));
end
continuationLogical = intersect( ...
    ["stress_ok", "flutter_ok", "trim_ok", "simulation_ok", ...
     "feasible", "pareto_case071", "fallback_used", ...
     "archive_verified"], ...
    string(continuation.Properties.VariableNames), "stable");
for column = continuationLogical
    continuation.(column) = to_logical_column(continuation.(column));
end

assert(height(evaluations) == expected.expected_total_evaluations, ...
    "Unexpected number of %s evaluation rows.", topology);
assert(height(continuation) == ...
    expected.expected_continuation_evaluations, ...
    "Unexpected number of %s continuation rows.", topology);
assert(isequal(evaluations.case_id, ...
    (1:expected.expected_total_evaluations)'), ...
    "%s evaluation case indices are not contiguous.", topology);
assert(isequal(continuation.case_id, ...
    (config.continuation_first_case:config.final_topology_case)'), ...
    "%s continuation case indices are not contiguous.", topology);
end

