function outputPaths = plot_observed_pareto( ...
        topology, evaluations, outputDirectory, continuationFirstCase)
%PLOT_OBSERVED_PARETO Plot the feasible finite-sample Pareto record.

topology = lower(string(topology));
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

objectives = [evaluations.mass_kg, evaluations.compliance_Nm];
feasible = evaluations.feasible;
pareto = observed_pareto_mask(objectives, feasible);
assert(isequal(pareto, evaluations.pareto_case071), ...
    "Stored and recomputed %s Pareto masks differ.", topology);

continuation = evaluations.case_id >= continuationFirstCase;
dominatedFeasible = feasible & ~pareto;
infeasible = ~feasible;
initialPareto = pareto & ~continuation;
continuationPareto = pareto & continuation;

colors = struct( ...
    "ink", [0.11, 0.14, 0.17], ...
    "grid", [0.88, 0.90, 0.92], ...
    "dominated", [0.64, 0.68, 0.72], ...
    "infeasible", [0.43, 0.47, 0.51], ...
    "initial", [0.12, 0.39, 0.63], ...
    "continuation", [0.85, 0.36, 0.05]);

figureHandle = figure(Visible="off", Color="white", ...
    Position=[100, 100, 900, 650]);
axesHandle = axes(figureHandle);
hold(axesHandle, "on");
grid(axesHandle, "on");
axesHandle.GridColor = colors.grid;
axesHandle.Layer = "top";

scatter(axesHandle, objectives(dominatedFeasible, 1), ...
    objectives(dominatedFeasible, 2), 38, colors.dominated, "o", ...
    "filled", MarkerEdgeColor="white", LineWidth=0.5, ...
    DisplayName=sprintf("Feasible, dominated (%d)", ...
        nnz(dominatedFeasible)));
scatter(axesHandle, objectives(infeasible, 1), ...
    objectives(infeasible, 2), 46, colors.infeasible, "x", ...
    LineWidth=1.2, DisplayName=sprintf("Infeasible (%d)", ...
        nnz(infeasible)));

paretoIndices = find(pareto);
[~, order] = sort(objectives(paretoIndices, 1));
orderedPareto = paretoIndices(order);
plot(axesHandle, objectives(orderedPareto, 1), ...
    objectives(orderedPareto, 2), Color=colors.ink, LineWidth=1.4, ...
    HandleVisibility="off");
scatter(axesHandle, objectives(initialPareto, 1), ...
    objectives(initialPareto, 2), 72, "o", MarkerFaceColor="white", ...
    MarkerEdgeColor=colors.initial, LineWidth=1.8, ...
    DisplayName=sprintf("Pareto, cases 1-51 (%d)", nnz(initialPareto)));
scatter(axesHandle, objectives(continuationPareto, 1), ...
    objectives(continuationPareto, 2), 72, "d", ...
    MarkerFaceColor=colors.continuation, MarkerEdgeColor="white", ...
    LineWidth=0.8, ...
    DisplayName=sprintf("Pareto, cases 52-71 (%d)", ...
        nnz(continuationPareto)));

xlabel(axesHandle, "Two-wing total mass [kg]");
ylabel(axesHandle, "Two-wing trim compliance [N m]");
title(axesHandle, sprintf("%s observed finite-sample Pareto set", ...
    upper(topology)), FontWeight="bold");
subtitle(axesHandle, ...
    "Cases 1-51 are inherited conditioning data; cases 52-71 are the reported continuation");
legend(axesHandle, Location="best", Box="off");
box(axesHandle, "on");
set(axesHandle, FontName="Times New Roman", FontSize=10);

stem = topology + "_observed_pareto";
outputPaths = struct( ...
    "png", fullfile(outputDirectory, stem + ".png"), ...
    "pdf", fullfile(outputDirectory, stem + ".pdf"));
exportgraphics(figureHandle, outputPaths.png, Resolution=220);
exportgraphics(figureHandle, outputPaths.pdf, ContentType="vector");
close(figureHandle);
end
