function [outputPaths, fitDiagnostics] = plot_feasibility_score( ...
        topology, evaluations, config, outputDirectory)
%PLOT_FEASIBILITY_SCORE Fit and plot the released binary-label score.

topology = lower(string(topology));
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

lowerBound = reshape(double(config.design_domain.lower_bound), 1, []);
upperBound = reshape(double(config.design_domain.upper_bound), 1, []);
X = [evaluations.a_m, evaluations.t1_over_a];
XUnit = (X - lowerBound) ./ (upperBound - lowerBound);
isFeasible = evaluations.feasible;

options = cTSEMOOptions();
[model, fitDiagnostics] = ctsemo.fitClippedBinaryPof( ...
    XUnit, isFeasible, options);
nGrid = double(config.grid_points_per_axis);
gridAxis = linspace(0, 1, nGrid);
[gridUnit1, gridUnit2] = meshgrid(gridAxis, gridAxis);
[scoreVector, ~] = ctsemo.predictClippedBinaryPof( ...
    model, [gridUnit1(:), gridUnit2(:)]);
scoreGrid = reshape(scoreVector, nGrid, nGrid);
gridPhysical1 = lowerBound(1) + ...
    gridUnit1 .* (upperBound(1) - lowerBound(1));
gridPhysical2 = lowerBound(2) + ...
    gridUnit2 .* (upperBound(2) - lowerBound(2));

pareto = observed_pareto_mask( ...
    [evaluations.mass_kg, evaluations.compliance_Nm], isFeasible);
continuation = evaluations.case_id >= config.continuation_first_case;
initialPareto = pareto & ~continuation;
continuationPareto = pareto & continuation;
dominatedFeasible = isFeasible & ~pareto;
infeasible = ~isFeasible;

colors = struct( ...
    "grid", [0.84, 0.87, 0.89], ...
    "dominated", [0.50, 0.54, 0.58], ...
    "infeasible", [0.57, 0.60, 0.63], ...
    "initial", [0.12, 0.39, 0.63], ...
    "continuation", [0.89, 0.31, 0.04]);
colorAnchors = [ ...
    0.06, 0.13, 0.24; ...
    0.05, 0.30, 0.39; ...
    0.34, 0.56, 0.44; ...
    0.75, 0.72, 0.34; ...
    1.00, 0.94, 0.67];
colorMap = interp1(linspace(0, 1, size(colorAnchors, 1)), ...
    colorAnchors, linspace(0, 1, 256), "pchip");

figureHandle = figure(Visible="off", Color="white", ...
    Position=[100, 100, 860, 780]);
axesHandle = axes(figureHandle);
hold(axesHandle, "on");
contourf(axesHandle, gridPhysical1, gridPhysical2, scoreGrid, ...
    linspace(0, 1, 26), LineStyle="none", HandleVisibility="off");
colormap(axesHandle, colorMap);
clim(axesHandle, [0, 1]);
colorbarHandle = colorbar(axesHandle);
colorbarHandle.Label.String = "Geometry-based feasibility score [-]";

scatter(axesHandle, X(dominatedFeasible, 1), X(dominatedFeasible, 2), ...
    28, "o", MarkerFaceColor="white", ...
    MarkerEdgeColor=colors.dominated, LineWidth=0.8, ...
    DisplayName=sprintf("Feasible, dominated (%d)", ...
        nnz(dominatedFeasible)));
scatter(axesHandle, X(infeasible, 1), X(infeasible, 2), ...
    34, "x", MarkerEdgeColor=colors.infeasible, LineWidth=1.0, ...
    DisplayName=sprintf("Infeasible (%d)", nnz(infeasible)));
scatter(axesHandle, X(initialPareto, 1), X(initialPareto, 2), ...
    64, "o", MarkerFaceColor="white", MarkerEdgeColor=colors.initial, ...
    LineWidth=1.8, ...
    DisplayName=sprintf("Pareto, cases 1-51 (%d)", nnz(initialPareto)));
scatter(axesHandle, X(continuationPareto, 1), ...
    X(continuationPareto, 2), 68, "d", ...
    MarkerFaceColor=colors.continuation, MarkerEdgeColor="white", ...
    LineWidth=0.7, ...
    DisplayName=sprintf("Pareto, cases 52-71 (%d)", ...
        nnz(continuationPareto)));

xlim(axesHandle, lowerBound([1, 1]) + [0, upperBound(1)-lowerBound(1)]);
ylim(axesHandle, lowerBound([2, 2]) + [0, upperBound(2)-lowerBound(2)]);
pbaspect(axesHandle, [1, 1, 1]);
grid(axesHandle, "on");
axesHandle.GridColor = colors.grid;
axesHandle.GridAlpha = 0.55;
axesHandle.Layer = "top";
box(axesHandle, "on");
xlabel(axesHandle, "a [m]");
ylabel(axesHandle, "t_1/a [-]", Interpreter="tex");
title(axesHandle, sprintf("%s binary-label feasibility score", ...
    upper(topology)), FontWeight="bold");
subtitle(axesHandle, ...
    "Square display of the complete two-input design domain");
legend(axesHandle, Location="southoutside", NumColumns=2, Box="off");
set(axesHandle, FontName="Times New Roman", FontSize=10);

stem = topology + "_feasibility_score";
outputPaths = struct( ...
    "png", fullfile(outputDirectory, stem + ".png"), ...
    "pdf", fullfile(outputDirectory, stem + ".pdf"));
exportgraphics(figureHandle, outputPaths.png, Resolution=220);
exportgraphics(figureHandle, outputPaths.pdf, ContentType="vector");
close(figureHandle);
end
