function summary = reproduce_planform(outputDirectory)
%REPRODUCE_PLANFORM Rebuild final planform plots from the frozen 50 rows.

if nargin < 1 || strlength(string(outputDirectory)) == 0
    outputDirectory = fullfile(artifact_repository_root(), ...
        "generated", "planform");
end
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

root = artifact_repository_root();
data = readtable(fullfile(root, "data", "planform", ...
    "evaluations_cases001_050.csv"), TextType="string", ...
    VariableNamingRule="preserve");
data.feasible = to_logical_column(data.feasible);
data.final_pareto = to_logical_column(data.final_pareto);
pareto = observed_pareto_mask([data.CDitrim, data.Ctrim_Nm], data.feasible);
assert(isequal(pareto, data.final_pareto), ...
    "Stored and recomputed planform Pareto masks differ.");

continuation = data.case > 40;
plotPlanformObjectives(data, pareto, continuation, outputDirectory);
plotPlanformDomain(data, pareto, continuation, outputDirectory);

summary = table("PLANFORM", height(data), nnz(data.feasible), ...
    nnz(pareto), 'VariableNames', ...
    ["Study", "Evaluations", "Feasible", "Pareto"]);
writetable(summary, fullfile(outputDirectory, "planform_summary.csv"));
end

function plotPlanformObjectives(data, pareto, continuation, outputDirectory)
figureHandle = figure(Visible="off", Color="white", ...
    Position=[100, 100, 900, 650]);
axesHandle = axes(figureHandle);
hold(axesHandle, "on");
scatter(axesHandle, data.CDitrim(~data.feasible), ...
    data.Ctrim_Nm(~data.feasible), 48, "x", ...
    MarkerEdgeColor=[0.42, 0.45, 0.48], LineWidth=1.2, ...
    DisplayName=sprintf("Infeasible (%d)", nnz(~data.feasible)));
scatter(axesHandle, data.CDitrim(data.feasible & ~pareto), ...
    data.Ctrim_Nm(data.feasible & ~pareto), 42, "o", ...
    MarkerFaceColor=[0.70, 0.73, 0.76], MarkerEdgeColor="white", ...
    DisplayName=sprintf("Feasible, dominated (%d)", ...
    nnz(data.feasible & ~pareto)));
scatter(axesHandle, data.CDitrim(pareto & ~continuation), ...
    data.Ctrim_Nm(pareto & ~continuation), 70, "o", ...
    MarkerFaceColor="white", MarkerEdgeColor=[0.12, 0.39, 0.63], ...
    LineWidth=1.7, DisplayName="Pareto, cases 1-40");
scatter(axesHandle, data.CDitrim(pareto & continuation), ...
    data.Ctrim_Nm(pareto & continuation), 72, "d", ...
    MarkerFaceColor=[0.85, 0.36, 0.05], MarkerEdgeColor="white", ...
    DisplayName="Pareto, cases 41-50");
xlabel(axesHandle, "Trim induced-drag coefficient [-]");
ylabel(axesHandle, "Two-wing trim compliance [N m]");
title(axesHandle, "Fixed-area planform observed Pareto set");
legend(axesHandle, Location="best", Box="off");
grid(axesHandle, "on"); box(axesHandle, "on");
set(axesHandle, FontName="Times New Roman", FontSize=10);
exportBoth(figureHandle, outputDirectory, "planform_observed_pareto");
end

function plotPlanformDomain(data, pareto, continuation, outputDirectory)
figureHandle = figure(Visible="off", Color="white", ...
    Position=[100, 100, 760, 720]);
axesHandle = axes(figureHandle);
hold(axesHandle, "on");
scatter(axesHandle, data.AR(~data.feasible), ...
    data.taper_ratio(~data.feasible), 48, "x", ...
    MarkerEdgeColor=[0.42, 0.45, 0.48], LineWidth=1.2, ...
    DisplayName="Infeasible");
scatter(axesHandle, data.AR(data.feasible & ~pareto), ...
    data.taper_ratio(data.feasible & ~pareto), 42, "o", ...
    MarkerFaceColor=[0.70, 0.73, 0.76], MarkerEdgeColor="white", ...
    DisplayName="Feasible, dominated");
scatter(axesHandle, data.AR(pareto & ~continuation), ...
    data.taper_ratio(pareto & ~continuation), 70, "o", ...
    MarkerFaceColor="white", MarkerEdgeColor=[0.12, 0.39, 0.63], ...
    LineWidth=1.7, DisplayName="Pareto, cases 1-40");
scatter(axesHandle, data.AR(pareto & continuation), ...
    data.taper_ratio(pareto & continuation), 72, "d", ...
    MarkerFaceColor=[0.85, 0.36, 0.05], MarkerEdgeColor="white", ...
    DisplayName="Pareto, cases 41-50");
xlim(axesHandle, [6, 12]); ylim(axesHandle, [0.2, 0.8]);
pbaspect(axesHandle, [1, 1, 1]);
xlabel(axesHandle, "Aspect ratio [-]");
ylabel(axesHandle, "Taper ratio [-]");
title(axesHandle, "Fixed-area planform design record");
legend(axesHandle, Location="southoutside", NumColumns=2, Box="off");
grid(axesHandle, "on"); box(axesHandle, "on");
set(axesHandle, FontName="Times New Roman", FontSize=10);
exportBoth(figureHandle, outputDirectory, "planform_design_space");
end

function exportBoth(figureHandle, outputDirectory, stem)
exportgraphics(figureHandle, fullfile(outputDirectory, stem + ".png"), ...
    Resolution=220);
exportgraphics(figureHandle, fullfile(outputDirectory, stem + ".pdf"), ...
    ContentType="vector");
close(figureHandle);
end
